### ISSUE TITLE
How can I set up a hosting instance of HyperHost ?

### ISSUE THREAD

**Issue by freedomtrain** [RationalCoding/HyperHost#6]
How can I set up a hosting instance of HyperHost on Debian ?

**Comment by t-mullen** [comment]
HyperHost runs in the browser and doesn't have a server. It does use some additional services though and you can run your own instances of these if you want.

1. Any static server to serve your client code. (I'm using gh-pages)
2. A [wzrd.in](https://wzrd.in/) server to fetch and browserify NPM modules
3. A [PeerJS](http://peerjs.com/) signalling server to do WebRTC signalling.

Inside src/config, you can point the client at these services.

Look at the gh-pages branch to see how the drag and drop hosting demo works.

**Comment by freedomtrain** [comment]
Thanks so much for your reply. 
What would we need to do to host an instance of MultiHack ?

**Comment by t-mullen** [comment]
It's just client-side Javascript. Try cloning the gh-pages branch and opening index.html in your browser.

You can serve the files as you would any other HTML and JS.
